// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjwfmOcYqJeu6gTNDA5COJkfqgXFawIGc',
    appId: '1:531387933797:android:85c0bb47fb723bc787d28c',
    messagingSenderId: '531387933797',
    projectId: 'paypact-fec8e',
    storageBucket: 'paypact-fec8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs8kMYqE5N2C_gFkWRwIM51ZMmnElnGlY',
    appId: '1:531387933797:ios:0ea51f18ed3d79c187d28c',
    messagingSenderId: '531387933797',
    projectId: 'paypact-fec8e',
    storageBucket: 'paypact-fec8e.firebasestorage.app',
    iosClientId: '531387933797-6r3upag01ihg89jokos6601s5mlkcg6u.apps.googleusercontent.com',
    iosBundleId: 'com.kshitijcodecraft.paypact',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4fsgbSrFNR0JstFXvd-aK_vyX742FKOM',
    appId: '1:531387933797:web:608c22793e00144387d28c',
    messagingSenderId: '531387933797',
    projectId: 'paypact-fec8e',
    authDomain: 'paypact-fec8e.firebaseapp.com',
    storageBucket: 'paypact-fec8e.firebasestorage.app',
    measurementId: 'G-HZ4E0L5KT6',
  );

}